//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationAccrobrancheProper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorie
    {
        public Categorie()
        {
            this.LesProduits = new List<Produit>();
        }
    
        public int idCategorie { get; set; }
        public string libelleCategorie { get; set; }
    
        public virtual List<Produit> LesProduits { get; set; }
    }
}
