//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationAccrobrancheProper
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Modele : DbContext
    {
        public Modele()
            : base("name=Modele")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Categorie> Categorie { get; set; }
        public DbSet<Fournisseur> Fournisseur { get; set; }
        public DbSet<LignedeVente> LignedeVente { get; set; }
        public DbSet<Produit> Produit { get; set; }
        public DbSet<Vente> Vente { get; set; }
    }
}
